---
    - name: Copy host-manager context.xml
      template:
        src: templates/myhostcontext.j2
        dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Copy manager context.xml
      template:
        src: templates/mycontext.j2
        dest: /opt/tomcat/webapps/manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Copy tomcat-users.xml
      template:
        src: templates/tomcat-users.j2
        dest: /opt/tomcat/conf/tomcat-users.xml
        owner: tomcat
        group: tomcat
        mode: '0644'
