---
    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /tmp/tomcat.tar.gz
        mode: '0644'

    - name: Create Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt/Tomcat
        remote_src: yes
        extra_opts:
          - --strip-components=1
