---
- name: Install Java using DNF
  tasks:
    - name: Update package cache
      dnf:
        update_cache: yes

    - name: Install Java 8
      dnf:
        name: java-1.8.0-openjdk
        state: present
